VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"

  # local ip of server
  config.vm.network :private_network, ip: "33.33.33.01"
  # share ../ directory
  config.vm.synced_folder "../../..", "/home/vagrant/Projects"

  config.ssh.forward_agent = true

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  config.vm.provider "virtualbox" do |vb|
    vb.name = "ruby_devbox"
    vb.memory = 1024
    vb.cpus = 2
  end


  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../ansible/ruby.yml"
    # just for Vagrant auto-deployments (it generates his own inventory)
    ansible.groups = {
    }
  end
end
